/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;

/**
 * This is a model class for CreatePaymentOriginRequest type.
 */
public class CreatePaymentOriginRequest {
    private OptionalNullable<String> brandId;
    private OptionalNullable<String> chargeId;

    /**
     * Default constructor.
     */
    public CreatePaymentOriginRequest() {
    }

    /**
     * Initialization constructor.
     * @param  brandId  String value for brandId.
     * @param  chargeId  String value for chargeId.
     */
    public CreatePaymentOriginRequest(
            String brandId,
            String chargeId) {
        this.brandId = OptionalNullable.of(brandId);
        this.chargeId = OptionalNullable.of(chargeId);
    }

    /**
     * Initialization constructor.
     * @param  brandId  String value for brandId.
     * @param  chargeId  String value for chargeId.
     */

    protected CreatePaymentOriginRequest(OptionalNullable<String> brandId,
            OptionalNullable<String> chargeId) {
        this.brandId = brandId;
        this.chargeId = chargeId;
    }

    /**
     * Internal Getter for BrandId.
     * @return Returns the Internal String
     */
    @JsonGetter("brand_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetBrandId() {
        return this.brandId;
    }

    /**
     * Getter for BrandId.
     * @return Returns the String
     */
    public String getBrandId() {
        return OptionalNullable.getFrom(brandId);
    }

    /**
     * Setter for BrandId.
     * @param brandId Value for String
     */
    @JsonSetter("brand_id")
    public void setBrandId(String brandId) {
        this.brandId = OptionalNullable.of(brandId);
    }

    /**
     * UnSetter for BrandId.
     */
    public void unsetBrandId() {
        brandId = null;
    }

    /**
     * Internal Getter for ChargeId.
     * @return Returns the Internal String
     */
    @JsonGetter("charge_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetChargeId() {
        return this.chargeId;
    }

    /**
     * Getter for ChargeId.
     * @return Returns the String
     */
    public String getChargeId() {
        return OptionalNullable.getFrom(chargeId);
    }

    /**
     * Setter for ChargeId.
     * @param chargeId Value for String
     */
    @JsonSetter("charge_id")
    public void setChargeId(String chargeId) {
        this.chargeId = OptionalNullable.of(chargeId);
    }

    /**
     * UnSetter for ChargeId.
     */
    public void unsetChargeId() {
        chargeId = null;
    }

    /**
     * Converts this CreatePaymentOriginRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreatePaymentOriginRequest [" + "brandId=" + brandId + ", chargeId=" + chargeId
                + "]";
    }

    /**
     * Builds a new {@link CreatePaymentOriginRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreatePaymentOriginRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder();
        builder.brandId = internalGetBrandId();
        builder.chargeId = internalGetChargeId();
        return builder;
    }

    /**
     * Class to build instances of {@link CreatePaymentOriginRequest}.
     */
    public static class Builder {
        private OptionalNullable<String> brandId;
        private OptionalNullable<String> chargeId;



        /**
         * Setter for brandId.
         * @param  brandId  String value for brandId.
         * @return Builder
         */
        public Builder brandId(String brandId) {
            this.brandId = OptionalNullable.of(brandId);
            return this;
        }

        /**
         * UnSetter for brandId.
         * @return Builder
         */
        public Builder unsetBrandId() {
            brandId = null;
            return this;
        }

        /**
         * Setter for chargeId.
         * @param  chargeId  String value for chargeId.
         * @return Builder
         */
        public Builder chargeId(String chargeId) {
            this.chargeId = OptionalNullable.of(chargeId);
            return this;
        }

        /**
         * UnSetter for chargeId.
         * @return Builder
         */
        public Builder unsetChargeId() {
            chargeId = null;
            return this;
        }

        /**
         * Builds a new {@link CreatePaymentOriginRequest} object using the set fields.
         * @return {@link CreatePaymentOriginRequest}
         */
        public CreatePaymentOriginRequest build() {
            return new CreatePaymentOriginRequest(brandId, chargeId);
        }
    }
}
