/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CursorPagingResponse type.
 */
public class CursorPagingResponse {
    private String forwardCursor;

    /**
     * Default constructor.
     */
    public CursorPagingResponse() {
        forwardCursor = "null";
    }

    /**
     * Initialization constructor.
     * @param  forwardCursor  String value for forwardCursor.
     */
    public CursorPagingResponse(
            String forwardCursor) {
        this.forwardCursor = forwardCursor;
    }

    /**
     * Getter for ForwardCursor.
     * Pagging by foward cursor
     * (https://docs.pagar.me/reference/pagina%C3%A7%C3%A3o-1#forward-cursor)
     * @return Returns the String
     */
    @JsonGetter("forward_cursor")
    public String getForwardCursor() {
        return forwardCursor;
    }

    /**
     * Setter for ForwardCursor.
     * Pagging by foward cursor
     * (https://docs.pagar.me/reference/pagina%C3%A7%C3%A3o-1#forward-cursor)
     * @param forwardCursor Value for String
     */
    @JsonSetter("forward_cursor")
    public void setForwardCursor(String forwardCursor) {
        this.forwardCursor = forwardCursor;
    }

    /**
     * Converts this CursorPagingResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CursorPagingResponse [" + "forwardCursor=" + forwardCursor + "]";
    }

    /**
     * Builds a new {@link CursorPagingResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CursorPagingResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(forwardCursor);
        return builder;
    }

    /**
     * Class to build instances of {@link CursorPagingResponse}.
     */
    public static class Builder {
        private String forwardCursor = "null";

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  forwardCursor  String value for forwardCursor.
         */
        public Builder(String forwardCursor) {
            this.forwardCursor = forwardCursor;
        }

        /**
         * Setter for forwardCursor.
         * @param  forwardCursor  String value for forwardCursor.
         * @return Builder
         */
        public Builder forwardCursor(String forwardCursor) {
            this.forwardCursor = forwardCursor;
            return this;
        }

        /**
         * Builds a new {@link CursorPagingResponse} object using the set fields.
         * @return {@link CursorPagingResponse}
         */
        public CursorPagingResponse build() {
            return new CursorPagingResponse(forwardCursor);
        }
    }
}
