/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for GetIntegrationResponse type.
 */
public class GetIntegrationResponse {
    private String code;

    /**
     * Default constructor.
     */
    public GetIntegrationResponse() {
    }

    /**
     * Initialization constructor.
     * @param  code  String value for code.
     */
    public GetIntegrationResponse(
            String code) {
        this.code = code;
    }

    /**
     * Getter for Code.
     * @return Returns the String
     */
    @JsonGetter("code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCode() {
        return code;
    }

    /**
     * Setter for Code.
     * @param code Value for String
     */
    @JsonSetter("code")
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Converts this GetIntegrationResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GetIntegrationResponse [" + "code=" + code + "]";
    }

    /**
     * Builds a new {@link GetIntegrationResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GetIntegrationResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .code(getCode());
        return builder;
    }

    /**
     * Class to build instances of {@link GetIntegrationResponse}.
     */
    public static class Builder {
        private String code;



        /**
         * Setter for code.
         * @param  code  String value for code.
         * @return Builder
         */
        public Builder code(String code) {
            this.code = code;
            return this;
        }

        /**
         * Builds a new {@link GetIntegrationResponse} object using the set fields.
         * @return {@link GetIntegrationResponse}
         */
        public GetIntegrationResponse build() {
            return new GetIntegrationResponse(code);
        }
    }
}
