/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for GetPaymentOriginResponse type.
 */
public class GetPaymentOriginResponse {
    private String chargeId;
    private String brandId;

    /**
     * Default constructor.
     */
    public GetPaymentOriginResponse() {
    }

    /**
     * Initialization constructor.
     * @param  chargeId  String value for chargeId.
     * @param  brandId  String value for brandId.
     */
    public GetPaymentOriginResponse(
            String chargeId,
            String brandId) {
        this.chargeId = chargeId;
        this.brandId = brandId;
    }

    /**
     * Getter for ChargeId.
     * @return Returns the String
     */
    @JsonGetter("charge_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getChargeId() {
        return chargeId;
    }

    /**
     * Setter for ChargeId.
     * @param chargeId Value for String
     */
    @JsonSetter("charge_id")
    public void setChargeId(String chargeId) {
        this.chargeId = chargeId;
    }

    /**
     * Getter for BrandId.
     * @return Returns the String
     */
    @JsonGetter("brand_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBrandId() {
        return brandId;
    }

    /**
     * Setter for BrandId.
     * @param brandId Value for String
     */
    @JsonSetter("brand_id")
    public void setBrandId(String brandId) {
        this.brandId = brandId;
    }

    /**
     * Converts this GetPaymentOriginResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GetPaymentOriginResponse [" + "chargeId=" + chargeId + ", brandId=" + brandId + "]";
    }

    /**
     * Builds a new {@link GetPaymentOriginResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GetPaymentOriginResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .chargeId(getChargeId())
                .brandId(getBrandId());
        return builder;
    }

    /**
     * Class to build instances of {@link GetPaymentOriginResponse}.
     */
    public static class Builder {
        private String chargeId;
        private String brandId;



        /**
         * Setter for chargeId.
         * @param  chargeId  String value for chargeId.
         * @return Builder
         */
        public Builder chargeId(String chargeId) {
            this.chargeId = chargeId;
            return this;
        }

        /**
         * Setter for brandId.
         * @param  brandId  String value for brandId.
         * @return Builder
         */
        public Builder brandId(String brandId) {
            this.brandId = brandId;
            return this;
        }

        /**
         * Builds a new {@link GetPaymentOriginResponse} object using the set fields.
         * @return {@link GetPaymentOriginResponse}
         */
        public GetPaymentOriginResponse build() {
            return new GetPaymentOriginResponse(chargeId, brandId);
        }
    }
}
