/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;
import java.time.LocalDateTime;
import me.pagar.api.DateTimeHelper;

/**
 * This is a model class for GetPayableResponse type.
 */
public class GetPayableResponse {
    private String id;
    private String status;
    private int amount;
    private OptionalNullable<Integer> fee;
    private OptionalNullable<Integer> anticipationFee;
    private OptionalNullable<Integer> fraudCoverageFee;
    private OptionalNullable<Integer> installment;
    private String gatewayId;
    private String chargeId;
    private String splitId;
    private String bulkAnticipationId;
    private OptionalNullable<String> anticipationId;
    private String recipientId;
    private String originatorModel;
    private String originatorModelId;
    private OptionalNullable<LocalDateTime> paymentDate;
    private LocalDateTime originalPaymentDate;
    private OptionalNullable<String> type;
    private String paymentMethod;
    private OptionalNullable<LocalDateTime> accrualAt;
    private LocalDateTime createdAt;
    private OptionalNullable<String> liquidationArrangementId;
    private String settlementId;
    private String paymentProfileId;

    /**
     * Default constructor.
     */
    public GetPayableResponse() {
        gatewayId = "null";
        chargeId = "null";
        splitId = "null";
        bulkAnticipationId = "null";
        originatorModel = "null";
        originatorModelId = "null";
        paymentMethod = "null";
        settlementId = "null";
        paymentProfileId = "null";
        liquidationArrangementId = OptionalNullable.of("null");
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  status  String value for status.
     * @param  amount  int value for amount.
     * @param  gatewayId  String value for gatewayId.
     * @param  chargeId  String value for chargeId.
     * @param  splitId  String value for splitId.
     * @param  bulkAnticipationId  String value for bulkAnticipationId.
     * @param  recipientId  String value for recipientId.
     * @param  originatorModel  String value for originatorModel.
     * @param  originatorModelId  String value for originatorModelId.
     * @param  originalPaymentDate  LocalDateTime value for originalPaymentDate.
     * @param  paymentMethod  String value for paymentMethod.
     * @param  createdAt  LocalDateTime value for createdAt.
     * @param  settlementId  String value for settlementId.
     * @param  paymentProfileId  String value for paymentProfileId.
     * @param  fee  Integer value for fee.
     * @param  anticipationFee  Integer value for anticipationFee.
     * @param  fraudCoverageFee  Integer value for fraudCoverageFee.
     * @param  installment  Integer value for installment.
     * @param  anticipationId  String value for anticipationId.
     * @param  paymentDate  LocalDateTime value for paymentDate.
     * @param  type  String value for type.
     * @param  accrualAt  LocalDateTime value for accrualAt.
     * @param  liquidationArrangementId  String value for liquidationArrangementId.
     */
    public GetPayableResponse(
            String id,
            String status,
            int amount,
            String gatewayId,
            String chargeId,
            String splitId,
            String bulkAnticipationId,
            String recipientId,
            String originatorModel,
            String originatorModelId,
            LocalDateTime originalPaymentDate,
            String paymentMethod,
            LocalDateTime createdAt,
            String settlementId,
            String paymentProfileId,
            Integer fee,
            Integer anticipationFee,
            Integer fraudCoverageFee,
            Integer installment,
            String anticipationId,
            LocalDateTime paymentDate,
            String type,
            LocalDateTime accrualAt,
            String liquidationArrangementId) {
        this.id = id;
        this.status = status;
        this.amount = amount;
        this.fee = OptionalNullable.of(fee);
        this.anticipationFee = OptionalNullable.of(anticipationFee);
        this.fraudCoverageFee = OptionalNullable.of(fraudCoverageFee);
        this.installment = OptionalNullable.of(installment);
        this.gatewayId = gatewayId;
        this.chargeId = chargeId;
        this.splitId = splitId;
        this.bulkAnticipationId = bulkAnticipationId;
        this.anticipationId = OptionalNullable.of(anticipationId);
        this.recipientId = recipientId;
        this.originatorModel = originatorModel;
        this.originatorModelId = originatorModelId;
        this.paymentDate = OptionalNullable.of(paymentDate);
        this.originalPaymentDate = originalPaymentDate;
        this.type = OptionalNullable.of(type);
        this.paymentMethod = paymentMethod;
        this.accrualAt = OptionalNullable.of(accrualAt);
        this.createdAt = createdAt;
        this.liquidationArrangementId = OptionalNullable.of(liquidationArrangementId);
        this.settlementId = settlementId;
        this.paymentProfileId = paymentProfileId;
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  status  String value for status.
     * @param  amount  int value for amount.
     * @param  gatewayId  String value for gatewayId.
     * @param  chargeId  String value for chargeId.
     * @param  splitId  String value for splitId.
     * @param  bulkAnticipationId  String value for bulkAnticipationId.
     * @param  recipientId  String value for recipientId.
     * @param  originatorModel  String value for originatorModel.
     * @param  originatorModelId  String value for originatorModelId.
     * @param  originalPaymentDate  LocalDateTime value for originalPaymentDate.
     * @param  paymentMethod  String value for paymentMethod.
     * @param  createdAt  LocalDateTime value for createdAt.
     * @param  settlementId  String value for settlementId.
     * @param  paymentProfileId  String value for paymentProfileId.
     * @param  fee  Integer value for fee.
     * @param  anticipationFee  Integer value for anticipationFee.
     * @param  fraudCoverageFee  Integer value for fraudCoverageFee.
     * @param  installment  Integer value for installment.
     * @param  anticipationId  String value for anticipationId.
     * @param  paymentDate  LocalDateTime value for paymentDate.
     * @param  type  String value for type.
     * @param  accrualAt  LocalDateTime value for accrualAt.
     * @param  liquidationArrangementId  String value for liquidationArrangementId.
     */

    protected GetPayableResponse(String id, String status, int amount, String gatewayId,
            String chargeId, String splitId, String bulkAnticipationId, String recipientId,
            String originatorModel, String originatorModelId, LocalDateTime originalPaymentDate,
            String paymentMethod, LocalDateTime createdAt, String settlementId,
            String paymentProfileId, OptionalNullable<Integer> fee,
            OptionalNullable<Integer> anticipationFee, OptionalNullable<Integer> fraudCoverageFee,
            OptionalNullable<Integer> installment, OptionalNullable<String> anticipationId,
            OptionalNullable<LocalDateTime> paymentDate, OptionalNullable<String> type,
            OptionalNullable<LocalDateTime> accrualAt,
            OptionalNullable<String> liquidationArrangementId) {
        this.id = id;
        this.status = status;
        this.amount = amount;
        this.fee = fee;
        this.anticipationFee = anticipationFee;
        this.fraudCoverageFee = fraudCoverageFee;
        this.installment = installment;
        this.gatewayId = gatewayId;
        this.chargeId = chargeId;
        this.splitId = splitId;
        this.bulkAnticipationId = bulkAnticipationId;
        this.anticipationId = anticipationId;
        this.recipientId = recipientId;
        this.originatorModel = originatorModel;
        this.originatorModelId = originatorModelId;
        this.paymentDate = paymentDate;
        this.originalPaymentDate = originalPaymentDate;
        this.type = type;
        this.paymentMethod = paymentMethod;
        this.accrualAt = accrualAt;
        this.createdAt = createdAt;
        this.liquidationArrangementId = liquidationArrangementId;
        this.settlementId = settlementId;
        this.paymentProfileId = paymentProfileId;
    }

    /**
     * Getter for Id.
     * Payable Identifier
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Payable Identifier
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Status.
     * Payable status
     * @return Returns the String
     */
    @JsonGetter("status")
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Payable status
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for Amount.
     * Payable amount in cents
     * @return Returns the int
     */
    @JsonGetter("amount")
    public int getAmount() {
        return amount;
    }

    /**
     * Setter for Amount.
     * Payable amount in cents
     * @param amount Value for int
     */
    @JsonSetter("amount")
    public void setAmount(int amount) {
        this.amount = amount;
    }

    /**
     * Internal Getter for Fee.
     * Payable fee amount in cents
     * @return Returns the Internal Integer
     */
    @JsonGetter("fee")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetFee() {
        return this.fee;
    }

    /**
     * Getter for Fee.
     * Payable fee amount in cents
     * @return Returns the Integer
     */
    public Integer getFee() {
        return OptionalNullable.getFrom(fee);
    }

    /**
     * Setter for Fee.
     * Payable fee amount in cents
     * @param fee Value for Integer
     */
    @JsonSetter("fee")
    public void setFee(Integer fee) {
        this.fee = OptionalNullable.of(fee);
    }

    /**
     * UnSetter for Fee.
     * Payable fee amount in cents
     */
    public void unsetFee() {
        fee = null;
    }

    /**
     * Internal Getter for AnticipationFee.
     * Antecipation fee amount in cents
     * @return Returns the Internal Integer
     */
    @JsonGetter("anticipation_fee")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetAnticipationFee() {
        return this.anticipationFee;
    }

    /**
     * Getter for AnticipationFee.
     * Antecipation fee amount in cents
     * @return Returns the Integer
     */
    public Integer getAnticipationFee() {
        return OptionalNullable.getFrom(anticipationFee);
    }

    /**
     * Setter for AnticipationFee.
     * Antecipation fee amount in cents
     * @param anticipationFee Value for Integer
     */
    @JsonSetter("anticipation_fee")
    public void setAnticipationFee(Integer anticipationFee) {
        this.anticipationFee = OptionalNullable.of(anticipationFee);
    }

    /**
     * UnSetter for AnticipationFee.
     * Antecipation fee amount in cents
     */
    public void unsetAnticipationFee() {
        anticipationFee = null;
    }

    /**
     * Internal Getter for FraudCoverageFee.
     * Fraud coverage fee amount in cents
     * @return Returns the Internal Integer
     */
    @JsonGetter("fraud_coverage_fee")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetFraudCoverageFee() {
        return this.fraudCoverageFee;
    }

    /**
     * Getter for FraudCoverageFee.
     * Fraud coverage fee amount in cents
     * @return Returns the Integer
     */
    public Integer getFraudCoverageFee() {
        return OptionalNullable.getFrom(fraudCoverageFee);
    }

    /**
     * Setter for FraudCoverageFee.
     * Fraud coverage fee amount in cents
     * @param fraudCoverageFee Value for Integer
     */
    @JsonSetter("fraud_coverage_fee")
    public void setFraudCoverageFee(Integer fraudCoverageFee) {
        this.fraudCoverageFee = OptionalNullable.of(fraudCoverageFee);
    }

    /**
     * UnSetter for FraudCoverageFee.
     * Fraud coverage fee amount in cents
     */
    public void unsetFraudCoverageFee() {
        fraudCoverageFee = null;
    }

    /**
     * Internal Getter for Installment.
     * Number of installment
     * @return Returns the Internal Integer
     */
    @JsonGetter("installment")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetInstallment() {
        return this.installment;
    }

    /**
     * Getter for Installment.
     * Number of installment
     * @return Returns the Integer
     */
    public Integer getInstallment() {
        return OptionalNullable.getFrom(installment);
    }

    /**
     * Setter for Installment.
     * Number of installment
     * @param installment Value for Integer
     */
    @JsonSetter("installment")
    public void setInstallment(Integer installment) {
        this.installment = OptionalNullable.of(installment);
    }

    /**
     * UnSetter for Installment.
     * Number of installment
     */
    public void unsetInstallment() {
        installment = null;
    }

    /**
     * Getter for GatewayId.
     * Payment gateway identifier
     * @return Returns the String
     */
    @JsonGetter("gateway_id")
    public String getGatewayId() {
        return gatewayId;
    }

    /**
     * Setter for GatewayId.
     * Payment gateway identifier
     * @param gatewayId Value for String
     */
    @JsonSetter("gateway_id")
    public void setGatewayId(String gatewayId) {
        this.gatewayId = gatewayId;
    }

    /**
     * Getter for ChargeId.
     * Charge identifier
     * @return Returns the String
     */
    @JsonGetter("charge_id")
    public String getChargeId() {
        return chargeId;
    }

    /**
     * Setter for ChargeId.
     * Charge identifier
     * @param chargeId Value for String
     */
    @JsonSetter("charge_id")
    public void setChargeId(String chargeId) {
        this.chargeId = chargeId;
    }

    /**
     * Getter for SplitId.
     * @return Returns the String
     */
    @JsonGetter("split_id")
    public String getSplitId() {
        return splitId;
    }

    /**
     * Setter for SplitId.
     * @param splitId Value for String
     */
    @JsonSetter("split_id")
    public void setSplitId(String splitId) {
        this.splitId = splitId;
    }

    /**
     * Getter for BulkAnticipationId.
     * @return Returns the String
     */
    @JsonGetter("bulk_anticipation_id")
    public String getBulkAnticipationId() {
        return bulkAnticipationId;
    }

    /**
     * Setter for BulkAnticipationId.
     * @param bulkAnticipationId Value for String
     */
    @JsonSetter("bulk_anticipation_id")
    public void setBulkAnticipationId(String bulkAnticipationId) {
        this.bulkAnticipationId = bulkAnticipationId;
    }

    /**
     * Internal Getter for AnticipationId.
     * @return Returns the Internal String
     */
    @JsonGetter("anticipation_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetAnticipationId() {
        return this.anticipationId;
    }

    /**
     * Getter for AnticipationId.
     * @return Returns the String
     */
    public String getAnticipationId() {
        return OptionalNullable.getFrom(anticipationId);
    }

    /**
     * Setter for AnticipationId.
     * @param anticipationId Value for String
     */
    @JsonSetter("anticipation_id")
    public void setAnticipationId(String anticipationId) {
        this.anticipationId = OptionalNullable.of(anticipationId);
    }

    /**
     * UnSetter for AnticipationId.
     */
    public void unsetAnticipationId() {
        anticipationId = null;
    }

    /**
     * Getter for RecipientId.
     * Recipient identifier
     * @return Returns the String
     */
    @JsonGetter("recipient_id")
    public String getRecipientId() {
        return recipientId;
    }

    /**
     * Setter for RecipientId.
     * Recipient identifier
     * @param recipientId Value for String
     */
    @JsonSetter("recipient_id")
    public void setRecipientId(String recipientId) {
        this.recipientId = recipientId;
    }

    /**
     * Getter for OriginatorModel.
     * @return Returns the String
     */
    @JsonGetter("originator_model")
    public String getOriginatorModel() {
        return originatorModel;
    }

    /**
     * Setter for OriginatorModel.
     * @param originatorModel Value for String
     */
    @JsonSetter("originator_model")
    public void setOriginatorModel(String originatorModel) {
        this.originatorModel = originatorModel;
    }

    /**
     * Getter for OriginatorModelId.
     * Originator model identifier
     * @return Returns the String
     */
    @JsonGetter("originator_model_id")
    public String getOriginatorModelId() {
        return originatorModelId;
    }

    /**
     * Setter for OriginatorModelId.
     * Originator model identifier
     * @param originatorModelId Value for String
     */
    @JsonSetter("originator_model_id")
    public void setOriginatorModelId(String originatorModelId) {
        this.originatorModelId = originatorModelId;
    }

    /**
     * Internal Getter for PaymentDate.
     * Payment Date
     * @return Returns the Internal LocalDateTime
     */
    @JsonGetter("payment_date")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Rfc8601DateTimeSerializer.class)
    protected OptionalNullable<LocalDateTime> internalGetPaymentDate() {
        return this.paymentDate;
    }

    /**
     * Getter for PaymentDate.
     * Payment Date
     * @return Returns the LocalDateTime
     */
    public LocalDateTime getPaymentDate() {
        return OptionalNullable.getFrom(paymentDate);
    }

    /**
     * Setter for PaymentDate.
     * Payment Date
     * @param paymentDate Value for LocalDateTime
     */
    @JsonSetter("payment_date")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setPaymentDate(LocalDateTime paymentDate) {
        this.paymentDate = OptionalNullable.of(paymentDate);
    }

    /**
     * UnSetter for PaymentDate.
     * Payment Date
     */
    public void unsetPaymentDate() {
        paymentDate = null;
    }

    /**
     * Getter for OriginalPaymentDate.
     * Original Payment Date
     * @return Returns the LocalDateTime
     */
    @JsonGetter("original_payment_date")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getOriginalPaymentDate() {
        return originalPaymentDate;
    }

    /**
     * Setter for OriginalPaymentDate.
     * Original Payment Date
     * @param originalPaymentDate Value for LocalDateTime
     */
    @JsonSetter("original_payment_date")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setOriginalPaymentDate(LocalDateTime originalPaymentDate) {
        this.originalPaymentDate = originalPaymentDate;
    }

    /**
     * Internal Getter for Type.
     * Type of payable
     * @return Returns the Internal String
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetType() {
        return this.type;
    }

    /**
     * Getter for Type.
     * Type of payable
     * @return Returns the String
     */
    public String getType() {
        return OptionalNullable.getFrom(type);
    }

    /**
     * Setter for Type.
     * Type of payable
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = OptionalNullable.of(type);
    }

    /**
     * UnSetter for Type.
     * Type of payable
     */
    public void unsetType() {
        type = null;
    }

    /**
     * Getter for PaymentMethod.
     * Payment method of transaction
     * @return Returns the String
     */
    @JsonGetter("payment_method")
    public String getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Setter for PaymentMethod.
     * Payment method of transaction
     * @param paymentMethod Value for String
     */
    @JsonSetter("payment_method")
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * Internal Getter for AccrualAt.
     * Date issuer identify payment
     * @return Returns the Internal LocalDateTime
     */
    @JsonGetter("accrual_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Rfc8601DateTimeSerializer.class)
    protected OptionalNullable<LocalDateTime> internalGetAccrualAt() {
        return this.accrualAt;
    }

    /**
     * Getter for AccrualAt.
     * Date issuer identify payment
     * @return Returns the LocalDateTime
     */
    public LocalDateTime getAccrualAt() {
        return OptionalNullable.getFrom(accrualAt);
    }

    /**
     * Setter for AccrualAt.
     * Date issuer identify payment
     * @param accrualAt Value for LocalDateTime
     */
    @JsonSetter("accrual_at")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setAccrualAt(LocalDateTime accrualAt) {
        this.accrualAt = OptionalNullable.of(accrualAt);
    }

    /**
     * UnSetter for AccrualAt.
     * Date issuer identify payment
     */
    public void unsetAccrualAt() {
        accrualAt = null;
    }

    /**
     * Getter for CreatedAt.
     * Creation date
     * @return Returns the LocalDateTime
     */
    @JsonGetter("created_at")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * Creation date
     * @param createdAt Value for LocalDateTime
     */
    @JsonSetter("created_at")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Internal Getter for LiquidationArrangementId.
     * @return Returns the Internal String
     */
    @JsonGetter("liquidation_arrangement_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetLiquidationArrangementId() {
        return this.liquidationArrangementId;
    }

    /**
     * Getter for LiquidationArrangementId.
     * @return Returns the String
     */
    public String getLiquidationArrangementId() {
        return OptionalNullable.getFrom(liquidationArrangementId);
    }

    /**
     * Setter for LiquidationArrangementId.
     * @param liquidationArrangementId Value for String
     */
    @JsonSetter("liquidation_arrangement_id")
    public void setLiquidationArrangementId(String liquidationArrangementId) {
        this.liquidationArrangementId = OptionalNullable.of(liquidationArrangementId);
    }

    /**
     * UnSetter for LiquidationArrangementId.
     */
    public void unsetLiquidationArrangementId() {
        liquidationArrangementId = null;
    }

    /**
     * Getter for SettlementId.
     * Settlement identifier (new in v7.x)
     * @return Returns the String
     */
    @JsonGetter("settlement_id")
    public String getSettlementId() {
        return settlementId;
    }

    /**
     * Setter for SettlementId.
     * Settlement identifier (new in v7.x)
     * @param settlementId Value for String
     */
    @JsonSetter("settlement_id")
    public void setSettlementId(String settlementId) {
        this.settlementId = settlementId;
    }

    /**
     * Getter for PaymentProfileId.
     * Operational identifier of merchant inside of payment platform (new in v7.x)
     * @return Returns the String
     */
    @JsonGetter("payment_profile_id")
    public String getPaymentProfileId() {
        return paymentProfileId;
    }

    /**
     * Setter for PaymentProfileId.
     * Operational identifier of merchant inside of payment platform (new in v7.x)
     * @param paymentProfileId Value for String
     */
    @JsonSetter("payment_profile_id")
    public void setPaymentProfileId(String paymentProfileId) {
        this.paymentProfileId = paymentProfileId;
    }

    /**
     * Converts this GetPayableResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GetPayableResponse [" + "id=" + id + ", status=" + status + ", amount=" + amount
                + ", gatewayId=" + gatewayId + ", chargeId=" + chargeId + ", splitId=" + splitId
                + ", bulkAnticipationId=" + bulkAnticipationId + ", recipientId=" + recipientId
                + ", originatorModel=" + originatorModel + ", originatorModelId="
                + originatorModelId + ", originalPaymentDate=" + originalPaymentDate
                + ", paymentMethod=" + paymentMethod + ", createdAt=" + createdAt
                + ", settlementId=" + settlementId + ", paymentProfileId=" + paymentProfileId
                + ", fee=" + fee + ", anticipationFee=" + anticipationFee + ", fraudCoverageFee="
                + fraudCoverageFee + ", installment=" + installment + ", anticipationId="
                + anticipationId + ", paymentDate=" + paymentDate + ", type=" + type
                + ", accrualAt=" + accrualAt + ", liquidationArrangementId="
                + liquidationArrangementId + "]";
    }

    /**
     * Builds a new {@link GetPayableResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GetPayableResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, status, amount, gatewayId, chargeId, splitId,
                bulkAnticipationId, recipientId, originatorModel, originatorModelId,
                originalPaymentDate, paymentMethod, createdAt, settlementId, paymentProfileId);
        builder.fee = internalGetFee();
        builder.anticipationFee = internalGetAnticipationFee();
        builder.fraudCoverageFee = internalGetFraudCoverageFee();
        builder.installment = internalGetInstallment();
        builder.anticipationId = internalGetAnticipationId();
        builder.paymentDate = internalGetPaymentDate();
        builder.type = internalGetType();
        builder.accrualAt = internalGetAccrualAt();
        builder.liquidationArrangementId = internalGetLiquidationArrangementId();
        return builder;
    }

    /**
     * Class to build instances of {@link GetPayableResponse}.
     */
    public static class Builder {
        private String id;
        private String status;
        private int amount;
        private String gatewayId = "null";
        private String chargeId = "null";
        private String splitId = "null";
        private String bulkAnticipationId = "null";
        private String recipientId;
        private String originatorModel = "null";
        private String originatorModelId = "null";
        private LocalDateTime originalPaymentDate;
        private String paymentMethod = "null";
        private LocalDateTime createdAt;
        private String settlementId = "null";
        private String paymentProfileId = "null";
        private OptionalNullable<Integer> fee;
        private OptionalNullable<Integer> anticipationFee;
        private OptionalNullable<Integer> fraudCoverageFee;
        private OptionalNullable<Integer> installment;
        private OptionalNullable<String> anticipationId;
        private OptionalNullable<LocalDateTime> paymentDate;
        private OptionalNullable<String> type;
        private OptionalNullable<LocalDateTime> accrualAt;
        private OptionalNullable<String> liquidationArrangementId = OptionalNullable.of("null");

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  status  String value for status.
         * @param  amount  int value for amount.
         * @param  gatewayId  String value for gatewayId.
         * @param  chargeId  String value for chargeId.
         * @param  splitId  String value for splitId.
         * @param  bulkAnticipationId  String value for bulkAnticipationId.
         * @param  recipientId  String value for recipientId.
         * @param  originatorModel  String value for originatorModel.
         * @param  originatorModelId  String value for originatorModelId.
         * @param  originalPaymentDate  LocalDateTime value for originalPaymentDate.
         * @param  paymentMethod  String value for paymentMethod.
         * @param  createdAt  LocalDateTime value for createdAt.
         * @param  settlementId  String value for settlementId.
         * @param  paymentProfileId  String value for paymentProfileId.
         */
        public Builder(String id, String status, int amount, String gatewayId, String chargeId,
                String splitId, String bulkAnticipationId, String recipientId,
                String originatorModel, String originatorModelId, LocalDateTime originalPaymentDate,
                String paymentMethod, LocalDateTime createdAt, String settlementId,
                String paymentProfileId) {
            this.id = id;
            this.status = status;
            this.amount = amount;
            this.gatewayId = gatewayId;
            this.chargeId = chargeId;
            this.splitId = splitId;
            this.bulkAnticipationId = bulkAnticipationId;
            this.recipientId = recipientId;
            this.originatorModel = originatorModel;
            this.originatorModelId = originatorModelId;
            this.originalPaymentDate = originalPaymentDate;
            this.paymentMethod = paymentMethod;
            this.createdAt = createdAt;
            this.settlementId = settlementId;
            this.paymentProfileId = paymentProfileId;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for amount.
         * @param  amount  int value for amount.
         * @return Builder
         */
        public Builder amount(int amount) {
            this.amount = amount;
            return this;
        }

        /**
         * Setter for gatewayId.
         * @param  gatewayId  String value for gatewayId.
         * @return Builder
         */
        public Builder gatewayId(String gatewayId) {
            this.gatewayId = gatewayId;
            return this;
        }

        /**
         * Setter for chargeId.
         * @param  chargeId  String value for chargeId.
         * @return Builder
         */
        public Builder chargeId(String chargeId) {
            this.chargeId = chargeId;
            return this;
        }

        /**
         * Setter for splitId.
         * @param  splitId  String value for splitId.
         * @return Builder
         */
        public Builder splitId(String splitId) {
            this.splitId = splitId;
            return this;
        }

        /**
         * Setter for bulkAnticipationId.
         * @param  bulkAnticipationId  String value for bulkAnticipationId.
         * @return Builder
         */
        public Builder bulkAnticipationId(String bulkAnticipationId) {
            this.bulkAnticipationId = bulkAnticipationId;
            return this;
        }

        /**
         * Setter for recipientId.
         * @param  recipientId  String value for recipientId.
         * @return Builder
         */
        public Builder recipientId(String recipientId) {
            this.recipientId = recipientId;
            return this;
        }

        /**
         * Setter for originatorModel.
         * @param  originatorModel  String value for originatorModel.
         * @return Builder
         */
        public Builder originatorModel(String originatorModel) {
            this.originatorModel = originatorModel;
            return this;
        }

        /**
         * Setter for originatorModelId.
         * @param  originatorModelId  String value for originatorModelId.
         * @return Builder
         */
        public Builder originatorModelId(String originatorModelId) {
            this.originatorModelId = originatorModelId;
            return this;
        }

        /**
         * Setter for originalPaymentDate.
         * @param  originalPaymentDate  LocalDateTime value for originalPaymentDate.
         * @return Builder
         */
        public Builder originalPaymentDate(LocalDateTime originalPaymentDate) {
            this.originalPaymentDate = originalPaymentDate;
            return this;
        }

        /**
         * Setter for paymentMethod.
         * @param  paymentMethod  String value for paymentMethod.
         * @return Builder
         */
        public Builder paymentMethod(String paymentMethod) {
            this.paymentMethod = paymentMethod;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  LocalDateTime value for createdAt.
         * @return Builder
         */
        public Builder createdAt(LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for settlementId.
         * @param  settlementId  String value for settlementId.
         * @return Builder
         */
        public Builder settlementId(String settlementId) {
            this.settlementId = settlementId;
            return this;
        }

        /**
         * Setter for paymentProfileId.
         * @param  paymentProfileId  String value for paymentProfileId.
         * @return Builder
         */
        public Builder paymentProfileId(String paymentProfileId) {
            this.paymentProfileId = paymentProfileId;
            return this;
        }

        /**
         * Setter for fee.
         * @param  fee  Integer value for fee.
         * @return Builder
         */
        public Builder fee(Integer fee) {
            this.fee = OptionalNullable.of(fee);
            return this;
        }

        /**
         * UnSetter for fee.
         * @return Builder
         */
        public Builder unsetFee() {
            fee = null;
            return this;
        }

        /**
         * Setter for anticipationFee.
         * @param  anticipationFee  Integer value for anticipationFee.
         * @return Builder
         */
        public Builder anticipationFee(Integer anticipationFee) {
            this.anticipationFee = OptionalNullable.of(anticipationFee);
            return this;
        }

        /**
         * UnSetter for anticipationFee.
         * @return Builder
         */
        public Builder unsetAnticipationFee() {
            anticipationFee = null;
            return this;
        }

        /**
         * Setter for fraudCoverageFee.
         * @param  fraudCoverageFee  Integer value for fraudCoverageFee.
         * @return Builder
         */
        public Builder fraudCoverageFee(Integer fraudCoverageFee) {
            this.fraudCoverageFee = OptionalNullable.of(fraudCoverageFee);
            return this;
        }

        /**
         * UnSetter for fraudCoverageFee.
         * @return Builder
         */
        public Builder unsetFraudCoverageFee() {
            fraudCoverageFee = null;
            return this;
        }

        /**
         * Setter for installment.
         * @param  installment  Integer value for installment.
         * @return Builder
         */
        public Builder installment(Integer installment) {
            this.installment = OptionalNullable.of(installment);
            return this;
        }

        /**
         * UnSetter for installment.
         * @return Builder
         */
        public Builder unsetInstallment() {
            installment = null;
            return this;
        }

        /**
         * Setter for anticipationId.
         * @param  anticipationId  String value for anticipationId.
         * @return Builder
         */
        public Builder anticipationId(String anticipationId) {
            this.anticipationId = OptionalNullable.of(anticipationId);
            return this;
        }

        /**
         * UnSetter for anticipationId.
         * @return Builder
         */
        public Builder unsetAnticipationId() {
            anticipationId = null;
            return this;
        }

        /**
         * Setter for paymentDate.
         * @param  paymentDate  LocalDateTime value for paymentDate.
         * @return Builder
         */
        public Builder paymentDate(LocalDateTime paymentDate) {
            this.paymentDate = OptionalNullable.of(paymentDate);
            return this;
        }

        /**
         * UnSetter for paymentDate.
         * @return Builder
         */
        public Builder unsetPaymentDate() {
            paymentDate = null;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = OptionalNullable.of(type);
            return this;
        }

        /**
         * UnSetter for type.
         * @return Builder
         */
        public Builder unsetType() {
            type = null;
            return this;
        }

        /**
         * Setter for accrualAt.
         * @param  accrualAt  LocalDateTime value for accrualAt.
         * @return Builder
         */
        public Builder accrualAt(LocalDateTime accrualAt) {
            this.accrualAt = OptionalNullable.of(accrualAt);
            return this;
        }

        /**
         * UnSetter for accrualAt.
         * @return Builder
         */
        public Builder unsetAccrualAt() {
            accrualAt = null;
            return this;
        }

        /**
         * Setter for liquidationArrangementId.
         * @param  liquidationArrangementId  String value for liquidationArrangementId.
         * @return Builder
         */
        public Builder liquidationArrangementId(String liquidationArrangementId) {
            this.liquidationArrangementId = OptionalNullable.of(liquidationArrangementId);
            return this;
        }

        /**
         * UnSetter for liquidationArrangementId.
         * @return Builder
         */
        public Builder unsetLiquidationArrangementId() {
            liquidationArrangementId = null;
            return this;
        }

        /**
         * Builds a new {@link GetPayableResponse} object using the set fields.
         * @return {@link GetPayableResponse}
         */
        public GetPayableResponse build() {
            return new GetPayableResponse(id, status, amount, gatewayId, chargeId, splitId,
                    bulkAnticipationId, recipientId, originatorModel, originatorModelId,
                    originalPaymentDate, paymentMethod, createdAt, settlementId, paymentProfileId,
                    fee, anticipationFee, fraudCoverageFee, installment, anticipationId,
                    paymentDate, type, accrualAt, liquidationArrangementId);
        }
    }
}
