/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.OptionalNullable;
import java.util.List;

/**
 * This is a model class for ListPayablesResponse type.
 */
public class ListPayablesResponse {
    private OptionalNullable<List<GetPayableResponse>> data;
    private CursorPagingResponse paging;

    /**
     * Default constructor.
     */
    public ListPayablesResponse() {
    }

    /**
     * Initialization constructor.
     * @param  paging  CursorPagingResponse value for paging.
     * @param  data  List of GetPayableResponse value for data.
     */
    public ListPayablesResponse(
            CursorPagingResponse paging,
            List<GetPayableResponse> data) {
        this.data = OptionalNullable.of(data);
        this.paging = paging;
    }

    /**
     * Initialization constructor.
     * @param  paging  CursorPagingResponse value for paging.
     * @param  data  List of GetPayableResponse value for data.
     */

    protected ListPayablesResponse(CursorPagingResponse paging,
            OptionalNullable<List<GetPayableResponse>> data) {
        this.data = data;
        this.paging = paging;
    }

    /**
     * Internal Getter for Data.
     * The payable object
     * @return Returns the Internal List of GetPayableResponse
     */
    @JsonGetter("data")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<List<GetPayableResponse>> internalGetData() {
        return this.data;
    }

    /**
     * Getter for Data.
     * The payable object
     * @return Returns the List of GetPayableResponse
     */
    public List<GetPayableResponse> getData() {
        return OptionalNullable.getFrom(data);
    }

    /**
     * Setter for Data.
     * The payable object
     * @param data Value for List of GetPayableResponse
     */
    @JsonSetter("data")
    public void setData(List<GetPayableResponse> data) {
        this.data = OptionalNullable.of(data);
    }

    /**
     * UnSetter for Data.
     * The payable object
     */
    public void unsetData() {
        data = null;
    }

    /**
     * Getter for Paging.
     * Cursor paging response
     * @return Returns the CursorPagingResponse
     */
    @JsonGetter("paging")
    public CursorPagingResponse getPaging() {
        return paging;
    }

    /**
     * Setter for Paging.
     * Cursor paging response
     * @param paging Value for CursorPagingResponse
     */
    @JsonSetter("paging")
    public void setPaging(CursorPagingResponse paging) {
        this.paging = paging;
    }

    /**
     * Converts this ListPayablesResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ListPayablesResponse [" + "paging=" + paging + ", data=" + data + "]";
    }

    /**
     * Builds a new {@link ListPayablesResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ListPayablesResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(paging);
        builder.data = internalGetData();
        return builder;
    }

    /**
     * Class to build instances of {@link ListPayablesResponse}.
     */
    public static class Builder {
        private CursorPagingResponse paging;
        private OptionalNullable<List<GetPayableResponse>> data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  paging  CursorPagingResponse value for paging.
         */
        public Builder(CursorPagingResponse paging) {
            this.paging = paging;
        }

        /**
         * Setter for paging.
         * @param  paging  CursorPagingResponse value for paging.
         * @return Builder
         */
        public Builder paging(CursorPagingResponse paging) {
            this.paging = paging;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  List of GetPayableResponse value for data.
         * @return Builder
         */
        public Builder data(List<GetPayableResponse> data) {
            this.data = OptionalNullable.of(data);
            return this;
        }

        /**
         * UnSetter for data.
         * @return Builder
         */
        public Builder unsetData() {
            data = null;
            return this;
        }

        /**
         * Builds a new {@link ListPayablesResponse} object using the set fields.
         * @return {@link ListPayablesResponse}
         */
        public ListPayablesResponse build() {
            return new ListPayablesResponse(paging, data);
        }
    }
}
