/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for UpdateRecipientCodeRequest type.
 */
public class UpdateRecipientCodeRequest {
    private String code;

    /**
     * Default constructor.
     */
    public UpdateRecipientCodeRequest() {
    }

    /**
     * Initialization constructor.
     * @param  code  String value for code.
     */
    public UpdateRecipientCodeRequest(
            String code) {
        this.code = code;
    }

    /**
     * Getter for Code.
     * Code
     * @return Returns the String
     */
    @JsonGetter("code")
    public String getCode() {
        return code;
    }

    /**
     * Setter for Code.
     * Code
     * @param code Value for String
     */
    @JsonSetter("code")
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Converts this UpdateRecipientCodeRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UpdateRecipientCodeRequest [" + "code=" + code + "]";
    }

    /**
     * Builds a new {@link UpdateRecipientCodeRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UpdateRecipientCodeRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(code);
        return builder;
    }

    /**
     * Class to build instances of {@link UpdateRecipientCodeRequest}.
     */
    public static class Builder {
        private String code;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  code  String value for code.
         */
        public Builder(String code) {
            this.code = code;
        }

        /**
         * Setter for code.
         * @param  code  String value for code.
         * @return Builder
         */
        public Builder code(String code) {
            this.code = code;
            return this;
        }

        /**
         * Builds a new {@link UpdateRecipientCodeRequest} object using the set fields.
         * @return {@link UpdateRecipientCodeRequest}
         */
        public UpdateRecipientCodeRequest build() {
            return new UpdateRecipientCodeRequest(code);
        }
    }
}
