/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.controllers;

import io.apimatic.core.ApiCall;
import io.apimatic.core.GlobalConfiguration;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import me.pagar.api.ApiHelper;
import me.pagar.api.DateTimeHelper;
import me.pagar.api.Server;
import me.pagar.api.exceptions.ApiException;
import me.pagar.api.http.request.HttpMethod;
import me.pagar.api.models.ListPayablesResponse;

/**
 * This class lists all the endpoints of the groups.
 */
public final class DefaultPayablesController extends BaseController implements PayablesController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public DefaultPayablesController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * @param  type  Optional parameter: Example:
     * @param  splitId  Optional parameter: Example:
     * @param  bulkAnticipationId  Optional parameter: Example:
     * @param  status  Optional parameter: Example:
     * @param  recipientId  Optional parameter: Example:
     * @param  chargeId  Optional parameter: Example:
     * @param  paymentDateUntil  Optional parameter: Example:
     * @param  paymentDateSince  Optional parameter: Example:
     * @param  updatedUntil  Optional parameter: Example:
     * @param  updatedSince  Optional parameter: Example:
     * @param  createdUntil  Optional parameter: Example:
     * @param  createdSince  Optional parameter: Example:
     * @param  liquidationArrangementId  Optional parameter: Example:
     * @param  size  Optional parameter: Example:
     * @param  gatewayId  Optional parameter: Example:
     * @return    Returns the ListPayablesResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ListPayablesResponse getPayables(
            final String type,
            final String splitId,
            final String bulkAnticipationId,
            final String status,
            final String recipientId,
            final String chargeId,
            final String paymentDateUntil,
            final LocalDateTime paymentDateSince,
            final LocalDateTime updatedUntil,
            final LocalDateTime updatedSince,
            final LocalDateTime createdUntil,
            final LocalDateTime createdSince,
            final String liquidationArrangementId,
            final Integer size,
            final Long gatewayId) throws ApiException, IOException {
        return prepareGetPayablesRequest(type, splitId, bulkAnticipationId, status, recipientId,
                chargeId, paymentDateUntil, paymentDateSince, updatedUntil, updatedSince,
                createdUntil, createdSince, liquidationArrangementId, size, gatewayId).execute();
    }

    /**
     * @param  type  Optional parameter: Example:
     * @param  splitId  Optional parameter: Example:
     * @param  bulkAnticipationId  Optional parameter: Example:
     * @param  status  Optional parameter: Example:
     * @param  recipientId  Optional parameter: Example:
     * @param  chargeId  Optional parameter: Example:
     * @param  paymentDateUntil  Optional parameter: Example:
     * @param  paymentDateSince  Optional parameter: Example:
     * @param  updatedUntil  Optional parameter: Example:
     * @param  updatedSince  Optional parameter: Example:
     * @param  createdUntil  Optional parameter: Example:
     * @param  createdSince  Optional parameter: Example:
     * @param  liquidationArrangementId  Optional parameter: Example:
     * @param  size  Optional parameter: Example:
     * @param  gatewayId  Optional parameter: Example:
     * @return    Returns the ListPayablesResponse response from the API call
     */
    public CompletableFuture<ListPayablesResponse> getPayablesAsync(
            final String type,
            final String splitId,
            final String bulkAnticipationId,
            final String status,
            final String recipientId,
            final String chargeId,
            final String paymentDateUntil,
            final LocalDateTime paymentDateSince,
            final LocalDateTime updatedUntil,
            final LocalDateTime updatedSince,
            final LocalDateTime createdUntil,
            final LocalDateTime createdSince,
            final String liquidationArrangementId,
            final Integer size,
            final Long gatewayId) {
        try {
            return prepareGetPayablesRequest(type, splitId, bulkAnticipationId, status, recipientId,
            chargeId, paymentDateUntil, paymentDateSince, updatedUntil, updatedSince, createdUntil,
            createdSince, liquidationArrangementId, size, gatewayId).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getPayables.
     */
    private ApiCall<ListPayablesResponse, ApiException> prepareGetPayablesRequest(
            final String type,
            final String splitId,
            final String bulkAnticipationId,
            final String status,
            final String recipientId,
            final String chargeId,
            final String paymentDateUntil,
            final LocalDateTime paymentDateSince,
            final LocalDateTime updatedUntil,
            final LocalDateTime updatedSince,
            final LocalDateTime createdUntil,
            final LocalDateTime createdSince,
            final String liquidationArrangementId,
            final Integer size,
            final Long gatewayId) {
        return new ApiCall.Builder<ListPayablesResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/payables")
                        .queryParam(param -> param.key("type")
                                .value(type).isRequired(false))
                        .queryParam(param -> param.key("split_id")
                                .value(splitId).isRequired(false))
                        .queryParam(param -> param.key("bulk_anticipation_id")
                                .value(bulkAnticipationId).isRequired(false))
                        .queryParam(param -> param.key("status")
                                .value(status).isRequired(false))
                        .queryParam(param -> param.key("recipient_id")
                                .value(recipientId).isRequired(false))
                        .queryParam(param -> param.key("charge_id")
                                .value(chargeId).isRequired(false))
                        .queryParam(param -> param.key("payment_date_until")
                                .value(paymentDateUntil).isRequired(false))
                        .queryParam(param -> param.key("payment_date_since")
                                .value(DateTimeHelper.toRfc8601DateTime(paymentDateSince)).isRequired(false))
                        .queryParam(param -> param.key("updated_until")
                                .value(DateTimeHelper.toRfc8601DateTime(updatedUntil)).isRequired(false))
                        .queryParam(param -> param.key("updated_since")
                                .value(DateTimeHelper.toRfc8601DateTime(updatedSince)).isRequired(false))
                        .queryParam(param -> param.key("created_until")
                                .value(DateTimeHelper.toRfc8601DateTime(createdUntil)).isRequired(false))
                        .queryParam(param -> param.key("created_since")
                                .value(DateTimeHelper.toRfc8601DateTime(createdSince)).isRequired(false))
                        .queryParam(param -> param.key("liquidation_arrangement_id")
                                .value(liquidationArrangementId).isRequired(false))
                        .queryParam(param -> param.key("size")
                                .value(size).isRequired(false))
                        .queryParam(param -> param.key("gateway_id")
                                .value(gatewayId).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("httpBasic"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, ListPayablesResponse.class))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}