/*
 * PagarmeApiSDKLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package me.pagar.api.controllers;

import java.io.IOException;
import java.time.LocalDateTime;
import java.util.concurrent.CompletableFuture;
import me.pagar.api.exceptions.ApiException;
import me.pagar.api.models.ListPayablesResponse;

/**
 * This interface lists all the endpoints of the group.
 * This can be overridden for the mock calls.
 */
public interface PayablesController {
    /**
     * @param  type  Optional parameter: Example:
     * @param  splitId  Optional parameter: Example:
     * @param  bulkAnticipationId  Optional parameter: Example:
     * @param  status  Optional parameter: Example:
     * @param  recipientId  Optional parameter: Example:
     * @param  chargeId  Optional parameter: Example:
     * @param  paymentDateUntil  Optional parameter: Example:
     * @param  paymentDateSince  Optional parameter: Example:
     * @param  updatedUntil  Optional parameter: Example:
     * @param  updatedSince  Optional parameter: Example:
     * @param  createdUntil  Optional parameter: Example:
     * @param  createdSince  Optional parameter: Example:
     * @param  liquidationArrangementId  Optional parameter: Example:
     * @param  size  Optional parameter: Example:
     * @param  gatewayId  Optional parameter: Example:
     * @return    Returns the ListPayablesResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    ListPayablesResponse getPayables(
            final String type,
            final String splitId,
            final String bulkAnticipationId,
            final String status,
            final String recipientId,
            final String chargeId,
            final String paymentDateUntil,
            final LocalDateTime paymentDateSince,
            final LocalDateTime updatedUntil,
            final LocalDateTime updatedSince,
            final LocalDateTime createdUntil,
            final LocalDateTime createdSince,
            final String liquidationArrangementId,
            final Integer size,
            final Long gatewayId) throws ApiException, IOException;

    /**
     * @param  type  Optional parameter: Example:
     * @param  splitId  Optional parameter: Example:
     * @param  bulkAnticipationId  Optional parameter: Example:
     * @param  status  Optional parameter: Example:
     * @param  recipientId  Optional parameter: Example:
     * @param  chargeId  Optional parameter: Example:
     * @param  paymentDateUntil  Optional parameter: Example:
     * @param  paymentDateSince  Optional parameter: Example:
     * @param  updatedUntil  Optional parameter: Example:
     * @param  updatedSince  Optional parameter: Example:
     * @param  createdUntil  Optional parameter: Example:
     * @param  createdSince  Optional parameter: Example:
     * @param  liquidationArrangementId  Optional parameter: Example:
     * @param  size  Optional parameter: Example:
     * @param  gatewayId  Optional parameter: Example:
     * @return    Returns the ListPayablesResponse response from the API call
     */
    CompletableFuture<ListPayablesResponse> getPayablesAsync(
            final String type,
            final String splitId,
            final String bulkAnticipationId,
            final String status,
            final String recipientId,
            final String chargeId,
            final String paymentDateUntil,
            final LocalDateTime paymentDateSince,
            final LocalDateTime updatedUntil,
            final LocalDateTime updatedSince,
            final LocalDateTime createdUntil,
            final LocalDateTime createdSince,
            final String liquidationArrangementId,
            final Integer size,
            final Long gatewayId);

}